
<input type="hidden" name="codigo"
    value="<?php echo $modelo->obtener_codigo(); ?>">

<div class="form-group">
    <label for="nombre">Nombre</label>
    <input type="text" class="form-control text-uppercase" id="nombre"
        name="nombre" minlength="6" maxlength="30"
        value="<?php echo $modelo->obtener_nombre(); ?>" required
        <?php echo (defined('ESTA_RELACIONADO') && ESTA_RELACIONADO) ?
            'readonly' : 'autofocus'; ?>>
    <div class="alert alert-danger alerta-peligro" role="alert"
        id="error-nombre">
    </div>
</div>

<div class="form-group">
    <label for="simbolo">Símbolo</label>
    <input type="text" class="form-control text-uppercase" id="simbolo"
        name="simbolo" minlength="1" maxlength="5"
        value="<?php echo $modelo->obtener_simbolo(); ?>" required
        <?php if (defined('ESTA_RELACIONADO') && ESTA_RELACIONADO)
            echo 'readonly'; ?>>
    <div class="alert alert-danger alerta-peligro" role="alert"
        id="error-simbolo">
    </div>
</div>

<div class="form-check mb-3">
    <input type="checkbox" class="form-check-input" id="divisible"
        name="divisible"
        <?php if ($modelo->es_divisible()) echo 'checked'; ?>
        <?php if (defined('ESTA_RELACIONADO') && ESTA_RELACIONADO)
            echo 'disabled readonly'; ?>>
    <label class="form-check-label" for="divisible">Divisible</label>
</div>

<div class="form-check mb-3">
    <input type="checkbox" class="form-check-input" id="vigente"
        name="vigente"
        <?php if ($modelo->esta_vigente()) echo 'checked'; ?>
        <?php if (defined('ESTA_RELACIONADO') && ESTA_RELACIONADO)
            echo 'autofocus'; ?>>
    <label class="form-check-label" for="vigente">Vigente</label>
</div>
