
<input type="hidden" name="codigo"
    value="<?php echo $modelo->obtener_codigo(); ?>">

<div class="form-group">
    <label for="departamen">Departamento<?php if (defined('ESTA_RELACIONADO') && !ESTA_RELACIONADO) echo '<i class="fas fa-asterisk ew-required"></i>'; ?></label>
    <select class="form-control text-uppercase" id="departamen"
            name="departamen" required
            <?php echo (defined('ESTA_RELACIONADO') && ESTA_RELACIONADO) ?
                'disabled' : 'autofocus'; ?>>
        <option value="0"></option>
        <?php
        foreach ($departamentos as $departamen) {
            ?>
            <option value="<?php echo $departamen->obtener_codigo(); ?>"<?php if ($departamen->obtener_codigo() === $modelo->obtener_departamen()) echo ' selected'; ?>><?php echo Utiles::escapar_salida($departamen->obtener_nombre()); ?></option>
            <?php
        }
        ?>
    </select>
    <div class="alert alert-danger alerta-peligro" role="alert"
        id="error-departamen">
    </div>
</div>

<div class="form-group">
    <label for="ciudad">Ciudad<?php if (defined('ESTA_RELACIONADO') && !ESTA_RELACIONADO) echo '<i class="fas fa-asterisk ew-required"></i>'; ?></label>
    <select class="form-control text-uppercase" id="ciudad"
            name="ciudad" required
            <?php if (defined('ESTA_RELACIONADO') && ESTA_RELACIONADO)
                echo 'disabled'; ?>>
        <option value="0"></option>
        <?php
        foreach ($ciudades as $ciudad) {
            ?>
            <option value="<?php echo $ciudad->obtener_codigo(); ?>"<?php if ($ciudad->obtener_codigo() === $modelo->obtener_ciudad()) echo ' selected'; ?>><?php echo Utiles::escapar_salida($ciudad->obtener_nombre()); ?></option>
            <?php
        }
        ?>
    </select>
    <div class="alert alert-danger alerta-peligro" role="alert"
        id="error-ciudad">
    </div>
</div>

<div class="form-group">
    <label for="nombre">Nombre</label>
    <input type="text" class="form-control text-uppercase" id="nombre"
        name="nombre" minlength="6" maxlength="30"
        value="<?php echo Utiles::escapar_salida($modelo->obtener_nombre()); ?>" required
        <?php if (defined('ESTA_RELACIONADO') && ESTA_RELACIONADO)
            echo 'readonly'; ?>>
    <div class="alert alert-danger alerta-peligro" role="alert"
        id="error-nombre">
    </div>
</div>

<div class="form-check mb-3">
    <input type="checkbox" class="form-check-input" id="vigente"
        name="vigente"
        <?php if ($modelo->esta_vigente()) echo 'checked'; ?>
        <?php if (defined('ESTA_RELACIONADO') && ESTA_RELACIONADO)
            echo 'autofocus'; ?>>
    <label class="form-check-label" for="vigente">Vigente</label>
</div>
