
<input type="hidden" name="codigo" value="0">

<div class="form-group">
    <label for="departamen">Departamento<i class="fas fa-asterisk ew-required"></i></label>
    <select class="form-control text-uppercase" id="departamen"
            name="departamen" required autofocus>
        <option value="0" selected></option>
        <?php
        foreach ($departamentos as $departamen) {
            ?>
            <option value="<?php echo $departamen->obtener_codigo(); ?>"><?php echo Utiles::escapar_salida($departamen->obtener_nombre()); ?></option>
            <?php
        }
        ?>
    </select>
    <div class="alert alert-danger alerta-peligro" role="alert"
        id="error-departamen">
    </div>
</div>

<div class="form-group">
    <label for="ciudad">Ciudad<i class="fas fa-asterisk ew-required"></i>  </label>
    <select class="form-control text-uppercase" id="ciudad"
            name="ciudad" required>
        <option value="0" selected></option>
        <?php
        foreach ($ciudades as $ciudad) {
            ?>
            <option value="<?php echo $ciudad->obtener_codigo(); ?>"><?php echo Utiles::escapar_salida($ciudad->obtener_nombre()); ?></option>
            <?php
        }
        ?>
    </select>
    <div class="alert alert-danger alerta-peligro" role="alert"
        id="error-ciudad">
    </div>
</div>

<div class="form-group">
    <label for="nombre">Nombre</label>
    <input type="text" class="form-control text-uppercase" id="nombre"
        name="nombre" minlength="6" maxlength="30" value="" required>
    <div class="alert alert-danger alerta-peligro" role="alert"
        id="error-nombre">
    </div>
</div>

<div class="form-check mb-3">
    <input type="checkbox" class="form-check-input" id="vigente"
        name="vigente" checked>
    <label class="form-check-label" for="vigente">Vigente</label>
</div>
