
<input type="hidden" name="codigo" <?php $validador->mostrar_codigo(); ?>>

<?php
if ($validador->obtener_error_codigo() !== '') {
    ?>
    <div class="form-group">
        <?php $validador->mostrar_error_codigo(); ?>
    </div>
    <?php
}
?>

<div class="form-group">
    <label for="departamen">Departamento<?php if ((defined('ESTA_RELACIONADO') && !ESTA_RELACIONADO) || !defined('ESTA_RELACIONADO')) echo '<i class="fas fa-asterisk ew-required"></i>'; ?></label>
    <select class="form-control text-uppercase" id="departamen"
            name="departamen" required
            <?php echo (defined('ESTA_RELACIONADO') && ESTA_RELACIONADO) ?
                'disabled' : 'autofocus'; ?>>
        <option value="0"></option>
        <?php
        foreach ($departamentos as $departamen) {
            ?>
            <option value="<?php echo $departamen->obtener_codigo(); ?>"<?php if ($departamen->obtener_codigo() === $validador->obtener_departamen()) echo ' selected'; ?>><?php echo Utiles::escapar_salida($departamen->obtener_nombre()); ?></option>
            <?php
        }
        ?>
    </select>
    <?php $validador->mostrar_error_departamen(); ?>
</div>

<div class="form-group">
    <label for="ciudad">Ciudad<?php if ((defined('ESTA_RELACIONADO') && !ESTA_RELACIONADO) || !defined('ESTA_RELACIONADO')) echo '<i class="fas fa-asterisk ew-required"></i>'; ?></label>
    <select class="form-control text-uppercase" id="ciudad"
            name="ciudad" required
            <?php if (defined('ESTA_RELACIONADO') && ESTA_RELACIONADO)
                echo 'disabled'; ?>>
        <option value="0"></option>
        <?php
        foreach ($ciudades as $ciudad) {
            ?>
            <option value="<?php echo $ciudad->obtener_codigo(); ?>"<?php if ($ciudad->obtener_codigo() === $validador->obtener_ciudad()) echo ' selected'; ?>><?php echo Utiles::escapar_salida($ciudad->obtener_nombre()); ?></option>
            <?php
        }
        ?>
    </select>
    <?php $validador->mostrar_error_ciudad(); ?>
</div>

<div class="form-group">
    <label for="nombre">Nombre</label>
    <input type="text" class="form-control text-uppercase" id="nombre"
        name="nombre" minlength="6" maxlength="30"
        <?php echo $validador->mostrar_nombre(); ?> required
        <?php if (defined('ESTA_RELACIONADO') && ESTA_RELACIONADO)
            echo 'readonly'; ?>>
    <?php $validador->mostrar_error_nombre(); ?>
</div>

<div class="form-check mb-3">
    <input type="checkbox" class="form-check-input" id="vigente"
        name="vigente" <?php $validador->mostrar_vigente(); ?>
        <?php if (defined('ESTA_RELACIONADO') && ESTA_RELACIONADO)
            echo 'autofocus'; ?>>
    <label class="form-check-label" for="vigente">Vigente</label>
</div>

<?php
if ($validador->obtener_error_vigente() !== '') {
    ?>
    <div class="form-group">
        <?php $validador->mostrar_error_vigente(); ?>
    </div>
    <?php
}
?>
