        <script src="<?php echo RUTA_JS ?>utiles.js"></script>
        <script src="<?php echo RUTA_JS ?>validadorBase.js"></script>
        <script>
            (function() {
                if (document.getElementById('error-nombre').innerHTML.trim() !== '')
                    utiles.mostrarElemento('error-nombre');
            })();

            const config = {
                ajax: '<?php echo SERVIDOR; ?>' + '/ajax/',
                modulo: 'motivo-clie'
            }
        </script>