        <script src="<?php echo RUTA_JS ?>utiles.js"></script>
        <script src="<?php echo RUTA_JS ?>modeloValidador.js"></script>
        <script>
            $(function() {
                if ($('#error-maquina').length)
                    if ($('#error-maquina').text().trim().length)
                        $('#error-maquina').css('display', 'block');

                if ($('#error-marca').length)
                    if ($('#error-marca').text().trim().length)
                        $('#error-marca').css('display', 'block');

                if ($('#error-nombre').length)
                    if ($('#error-nombre').text().trim().length)
                        $('#error-nombre').css('display', 'block');

                if ($('#maquina').prop('type') == 'select-one')
                    $('#maquina').select2({
                        language: 'es',
                        theme: 'bootstrap4'
                    });

                if ($('#marca').prop('type') === 'select-one')
                    $('#marca').select2({
                        language: 'es',
                        theme: 'bootstrap4'
                    });

                $(window).resize(function() {
                    $('.select2').css('width', '100%');
                });
            });
        </script>
