
<?php
if (isset($mensaje) && !empty($mensaje))
    Utiles::mostrar_mensaje($mensaje);
?>

<input type="hidden" name="codigo"
    value="<?php echo $modelo->obtener_codigo(); ?>">

<div class="form-group">
    <label for="maquina">Máquina</label>
    <select class="form-control text-uppercase" id="maquina" disabled>
        <option value="<?php echo $modelo->obtener_maquina(); ?>" selected><?php echo Utiles::escapar_salida($maquina->obtener_nombre()); ?></option>
    </select>
</div>

<div class="form-group">
    <label for="marca">Marca</label>
    <select class="form-control text-uppercase" id="marca" disabled>
        <option value="<?php echo $modelo->obtener_marca(); ?>" selected><?php echo Utiles::escapar_salida($marca->obtener_nombre()); ?></option>
    </select>
</div>

<div class="form-group">
    <label for="nombre">Nombre</label>
    <input type="text" class="form-control text-uppercase" id="nombre"
        value="<?php echo Utiles::escapar_salida($modelo->obtener_nombre()); ?>" readonly>
</div>

<div class="form-check mb-3">
    <input type="checkbox" class="form-check-input" id="vigente"
        <?php if ($modelo->esta_vigente()) echo 'checked'; ?>
        disabled readonly>
    <label class="form-check-label" for="vigente">Vigente</label>
</div>
