
<input type="hidden" name="codigo" <?php $validador->mostrar_codigo(); ?>>

<?php
if ($validador->obtener_error_codigo() !== '') {
    ?>
    <div class="form-group">
        <?php $validador->mostrar_error_codigo(); ?>
    </div>
    <?php
}
?>

<div class="form-group">
    <label for="maquina">Máquina<?php if ((defined('ESTA_RELACIONADO') && !ESTA_RELACIONADO) || !defined('ESTA_RELACIONADO')) echo '<i class="fas fa-asterisk ew-required"></i>'; ?></label>
    <select class="form-control text-uppercase" id="maquina"
            name="maquina" required
            <?php echo (defined('ESTA_RELACIONADO') && ESTA_RELACIONADO) ?
                'disabled' : 'autofocus'; ?>>
        <option value="0"></option>
        <?php
        foreach ($maquinas as $maquina) {
            ?>
            <option value="<?php echo $maquina->obtener_codigo(); ?>"<?php if ($maquina->obtener_codigo() === $validador->obtener_maquina()) echo ' selected'; ?>><?php echo Utiles::escapar_salida($maquina->obtener_nombre()); ?></option>
            <?php
        }
        ?>
    </select>
    <?php $validador->mostrar_error_maquina(); ?>
</div>

<div class="form-group">
    <label for="marca">Marca<?php if ((defined('ESTA_RELACIONADO') && !ESTA_RELACIONADO) || !defined('ESTA_RELACIONADO')) echo '<i class="fas fa-asterisk ew-required"></i>'; ?></label>
    <select class="form-control text-uppercase" id="marca"
            name="marca" required
            <?php if (defined('ESTA_RELACIONADO') && ESTA_RELACIONADO)
                echo 'disabled'; ?>>
        <option value="0"></option>
        <?php
        foreach ($marcas as $marca) {
            ?>
            <option value="<?php echo $marca->obtener_codigo(); ?>"<?php if ($marca->obtener_codigo() === $validador->obtener_marca()) echo ' selected'; ?>><?php echo Utiles::escapar_salida($marca->obtener_nombre()); ?></option>
            <?php
        }
        ?>
    </select>
    <?php $validador->mostrar_error_marca(); ?>
</div>

<div class="form-group">
    <label for="nombre">Nombre</label>
    <input type="text" class="form-control text-uppercase" id="nombre"
        name="nombre" minlength="3" maxlength="30"
        <?php echo $validador->mostrar_nombre(); ?> required
        <?php if (defined('ESTA_RELACIONADO') && ESTA_RELACIONADO)
            echo 'readonly'; ?>>
    <?php $validador->mostrar_error_nombre(); ?>
</div>

<div class="form-check mb-3">
    <input type="checkbox" class="form-check-input" id="vigente"
        name="vigente" <?php $validador->mostrar_vigente(); ?>
        <?php if (defined('ESTA_RELACIONADO') && ESTA_RELACIONADO)
            echo 'autofocus'; ?>>
    <label class="form-check-label" for="vigente">Vigente</label>
</div>

<?php
if ($validador->obtener_error_vigente() !== '') {
    ?>
    <div class="form-group">
        <?php $validador->mostrar_error_vigente(); ?>
    </div>
    <?php
}
?>
