
<input type="hidden" name="codigo" value="0">

<div class="form-group row">
    <label for="nombre" class="col-3 col-form-label">Nombre</label>
    <div class="col-9">
        <input type="text" class="form-control text-uppercase" id="nombre"
            name="nombre" minlength="6" maxlength="30" value=""
            required autofocus>
        <div class="alert alert-danger alerta-peligro" role="alert"
            id="error-nombre">
        </div>
    </div>
</div>

<div class="form-group row">
    <label for="p1" class="col-3 col-form-label">&#37; 1</label>
    <div class="col-9">
        <input type="number" class="form-control" id="p1" name="p1"
            min="0.00" max="999.99" step="0.01" value="0.00">
        <div class="alert alert-danger alerta-peligro" role="alert"
            id="error-p1">
        </div>
    </div>
</div>

<div class="form-group row">
    <label for="p2" class="col-3 col-form-label">&#37; 2</label>
    <div class="col-9">
        <input type="number" class="form-control" id="p2" name="p2"
            min="0.00" max="999.99" step="0.01" value="0.00">
        <div class="alert alert-danger alerta-peligro" role="alert"
            id="error-p2">
        </div>
    </div>
</div>

<div class="form-group row">
    <label for="p3" class="col-3 col-form-label">&#37; 3</label>
    <div class="col-9">
        <input type="number" class="form-control" id="p3" name="p3"
            min="0.00" max="999.99" step="0.01" value="0.00">
        <div class="alert alert-danger alerta-peligro" role="alert"
            id="error-p3">
        </div>
    </div>
</div>

<div class="form-group row">
    <label for="p4" class="col-3 col-form-label">&#37; 4</label>
    <div class="col-9">
        <input type="number" class="form-control" id="p4" name="p4"
            min="0.00" max="999.99" step="0.01" value="0.00">
        <div class="alert alert-danger alerta-peligro" role="alert"
            id="error-p4">
        </div>
    </div>
</div>

<div class="form-group row">
    <label for="p5" class="col-3 col-form-label">&#37; 5</label>
    <div class="col-9">
        <input type="number" class="form-control" id="p5" name="p5"
            min="0.00" max="999.99" step="0.01" value="0.00">
        <div class="alert alert-danger alerta-peligro" role="alert"
            id="error-p5">
        </div>
    </div>
</div>

<div class="form-group row">
    <div class="col-3"></div>
    <div class="col-9">
        <div class="form-check">
            <input type="checkbox" class="form-check-input" id="vigente"
                name="vigente" checked>
            <label class="form-check-label" for="vigente">Vigente</label>
        </div>
    </div>
</div>
