        <script src="<?php echo RUTA_JS ?>utiles.js"></script>
        <script src="<?php echo RUTA_JS ?>familiaValidador.js"></script>
        <script>
            $(function() {
                if ($('#error-nombre').length)
                    if ($('#error-nombre').text().trim().length)
                        $('#error-nombre').css('display', 'block');

                if ($('#error-p1').length)
                    if ($('#error-p1').text().trim().length)
                        $('#error-p1').css('display', 'block');

                if ($('#error-p2').length)
                    if ($('#error-p2').text().trim().length)
                        $('#error-p2').css('display', 'block');

                if ($('#error-p3').length)
                    if ($('#error-p3').text().trim().length)
                        $('#error-p3').css('display', 'block');

                if ($('#error-p4').length)
                    if ($('#error-p4').text().trim().length)
                        $('#error-p4').css('display', 'block');

                if ($('#error-p5').length)
                    if ($('#error-p5').text().trim().length)
                        $('#error-p5').css('display', 'block');
            });
        </script>
