
<?php
if (isset($mensaje) && !empty($mensaje))
    Utiles::mostrar_mensaje($mensaje);
?>

<input type="hidden" name="codigo"
    value="<?php echo $modelo->obtener_codigo(); ?>">

<div class="form-group row">
    <label for="nombre" class="col-3 col-form-label">Nombre</label>
    <div class="col-9">
        <input type="text" class="form-control text-uppercase" id="nombre"
            value="<?php echo Utiles::escapar_salida($modelo->obtener_nombre()); ?>" readonly>
    </div>
</div>

<div class="form-group row">
    <label for="p1" class="col-3 col-form-label">&#37; 1</label>
    <div class="col-9">
        <input type="number" class="form-control" id="p1"
            value="<?php echo $modelo->obtener_p1(); ?>" readonly>
    </div>
</div>

<div class="form-group row">
    <label for="p2" class="col-3 col-form-label">&#37; 2</label>
    <div class="col-9">
        <input type="number" class="form-control" id="p2"
            value="<?php echo $modelo->obtener_p2(); ?>" readonly>
    </div>
</div>

<div class="form-group row">
    <label for="p3" class="col-3 col-form-label">&#37; 3</label>
    <div class="col-9">
        <input type="number" class="form-control" id="p3"
            value="<?php echo $modelo->obtener_p3(); ?>" readonly>
    </div>
</div>

<div class="form-group row">
    <label for="p4" class="col-3 col-form-label">&#37; 4</label>
    <div class="col-9">
        <input type="number" class="form-control" id="p4"
            value="<?php echo $modelo->obtener_p4(); ?>" readonly>
    </div>
</div>

<div class="form-group row">
    <label for="p5" class="col-3 col-form-label">&#37; 5</label>
    <div class="col-9">
        <input type="number" class="form-control" id="p5"
            value="<?php echo $modelo->obtener_p5(); ?>" readonly>
    </div>
</div>

<div class="form-group row">
    <div class="col-3"></div>
    <div class="col-9">
        <div class="form-check">
            <input type="checkbox" class="form-check-input" id="vigente"
                <?php if ($modelo->esta_vigente()) echo 'checked'; ?>
                disabled readonly>
            <label class="form-check-label" for="vigente">Vigente</label>
        </div>
    </div>
</div>
