
<input type="hidden" name="codigo" <?php $validador->mostrar_codigo(); ?>>

<?php
if ($validador->obtener_error_codigo() !== '') {
    ?>
    <div class="form-group">
        <?php $validador->mostrar_error_codigo(); ?>
    </div>
    <?php
}
?>

<div class="form-group row">
    <label for="nombre" class="col-3 col-form-label">Nombre</label>
    <div class="col-9">
        <input type="text" class="form-control text-uppercase" id="nombre"
            name="nombre" minlength="6" maxlength="30"
            <?php echo $validador->mostrar_nombre(); ?> required
            <?php echo (defined('ESTA_RELACIONADO') && ESTA_RELACIONADO) ?
                'readonly' : 'autofocus'; ?>>
        <?php $validador->mostrar_error_nombre(); ?>
    </div>
</div>

<div class="form-group row">
    <label for="p1" class="col-3 col-form-label">&#37; 1</label>
    <div class="col-9">
        <input type="number" class="form-control" id="p1" name="p1"
            min="0.00" max="999.99" step="0.01"
            <?php echo $validador->mostrar_p1(); ?>
            <?php if (defined('ESTA_RELACIONADO') && ESTA_RELACIONADO)
                echo 'autofocus'; ?>>
        <?php $validador->mostrar_error_p1(); ?>
    </div>
</div>

<div class="form-group row">
    <label for="p2" class="col-3 col-form-label">&#37; 2</label>
    <div class="col-9">
        <input type="number" class="form-control" id="p2" name="p2"
            min="0.00" max="999.99" step="0.01"
            <?php echo $validador->mostrar_p2(); ?>>
        <?php $validador->mostrar_error_p2(); ?>
    </div>
</div>

<div class="form-group row">
    <label for="p3" class="col-3 col-form-label">&#37; 3</label>
    <div class="col-9">
        <input type="number" class="form-control" id="p3" name="p3"
            min="0.00" max="999.99" step="0.01"
            <?php echo $validador->mostrar_p3(); ?>>
        <?php $validador->mostrar_error_p3(); ?>
    </div>
</div>

<div class="form-group row">
    <label for="p4" class="col-3 col-form-label">&#37; 4</label>
    <div class="col-9">
        <input type="number" class="form-control" id="p4" name="p4"
            min="0.00" max="999.99" step="0.01"
            <?php echo $validador->mostrar_p4(); ?>>
        <?php $validador->mostrar_error_p4(); ?>
    </div>
</div>

<div class="form-group row">
    <label for="p5" class="col-3 col-form-label">&#37; 5</label>
    <div class="col-9">
        <input type="number" class="form-control" id="p5" name="p5"
            min="0.00" max="999.99" step="0.01"
            <?php echo $validador->mostrar_p5(); ?>>
        <?php $validador->mostrar_error_p5(); ?>
    </div>
</div>

<div class="form-group row">
    <div class="col-3"></div>
    <div class="col-9">
        <div class="form-check">
            <input type="checkbox" class="form-check-input" id="vigente"
                name="vigente" <?php $validador->mostrar_vigente(); ?>>
            <label class="form-check-label" for="vigente">Vigente</label>
        </div>
    </div>
</div>

<?php
if ($validador->obtener_error_vigente() !== '') {
    ?>
    <div class="form-group">
        <?php $validador->mostrar_error_vigente(); ?>
    </div>
    <?php
}
?>
