<?php
header($_SERVER['SERVER_PROTOCOL'] . ' 403 Forbidden', true, 403);

include_once 'app/nucleo/config.inc.php';
include_once 'app/nucleo/Utiles.inc.php';

$titulo = '403 - Prohibido';

include_once 'plantillas/documento_declaracion.inc.phtml';
?>

<div class="container">
    <div class="row">
        <div class="card mx-auto mt-4">
            <div class="card-header text-danger">
                <h4><i class="far fa-hand-paper"></i> Error 403</h4>
            </div>
            <div class="card-body">
                <h5 class="card-title">¡Prohibido!</h5>
                <p class="card-text text-secondary text-justify">No tienes permiso para acceder al recurso que solicitaste en este servidor.</p>
                <a href="<?php echo SERVIDOR; ?>" class="btn btn-primary"><i class="fas fa-home"></i> Ir al inicio</a>
            </div>
        </div>
    </div>
</div>

<?php
include_once 'plantillas/documento_javascript.inc.phtml';
include_once 'plantillas/documento_cierre.inc.phtml';
?>