<?php
header($_SERVER['SERVER_PROTOCOL'] . ' 404 Not Found', true, 404);

include_once 'app/nucleo/config.inc.php';
include_once 'app/nucleo/Utiles.inc.php';

$titulo = '404 - Página no encontrada';

include_once 'plantillas/documento_declaracion.inc.phtml';
?>

<div class="container">
    <div class="row">
        <div class="card mx-auto mt-4">
            <div class="card-header text-danger">
                <h4><i class="fas fa-unlink"></i> Error 404</h4>
            </div>
            <div class="card-body">
                <h5 class="card-title">¡Página no encontrada!</h5>
                <p class="card-text text-secondary text-justify">Asegúrate de escribir la dirección de la página correctamente o vuelve a la página anterior.</p>
                <a href="<?php echo SERVIDOR; ?>" class="btn btn-primary"><i class="fas fa-home"></i> Ir al inicio</a>
            </div>
        </div>
    </div>
</div>

<?php
include_once 'plantillas/documento_javascript.inc.phtml';
include_once 'plantillas/documento_cierre.inc.phtml';
?>