<?php
header($_SERVER['SERVER_PROTOCOL'] . ' 403 Forbidden', true, 403);

include_once 'app/nucleo/config.inc.php';
include_once 'app/nucleo/Utiles.inc.php';

$titulo = 'Error de token CSRF';

include_once 'plantillas/documento_declaracion.inc.phtml';
?>

<div class="container">
    <div class="row">
        <div class="card mx-auto mt-4" style="max-width: 40rem;">
            <div class="card-header text-danger">
                <h4><i class="fas fa-shield-alt"></i> Comprobación de token CSRF</h4>
            </div>
            <div class="card-body">
                <h5 class="card-title">¡La comprobación ha fallado!</h5>
                <p class="card-text text-secondary text-justify">Token no válido o faltante.</p>
                <p class="card-text text-secondary text-justify">La sesión del formulario puede haber expirado, las cookies pueden no estar habilitadas o un posible ataque basado en CSRF.</p>
                <a href="<?php echo SERVIDOR; ?>" class="btn btn-primary"><i class="fas fa-home"></i> Ir al inicio</a>
            </div>
        </div>
    </div>
</div>

<?php
include_once 'plantillas/documento_javascript.inc.phtml';
include_once 'plantillas/documento_cierre.inc.phtml';
?>
