
<footer class="pie-pagina bg-dark fixed-bottom">
    <div class="container-fluid">
        <div class="d-flex justify-content-between">
            <div>
                <small class="d-inline d-sm-none">A & A</small>
                <small class="d-none d-sm-inline"><?php echo NOMBRE_EMPRESA; ?></small>
                <small class="text-muted"> - <?php echo NOMBRE_SISTEMA; ?> 0.0.0.1</small>
            </div>
            <div>
                <span>
                    <a href="https://www.facebook.com/ayaimportaciones/" title="Facebook" target="_blank" class="text-light">
                        <i class="fab fa-facebook-f"></i>
                    </a>
                </span>
                |
                <span>
                    <a href="https://www.instagram.com/ayaimportacionessrl/" title="Instagram" target="_blank" class="text-light">
                        <i class="fab fa-instagram"></i>
                    </a>
                </span>
                |
                <span>
                    <a href="http://www.ayaimportaciones.com.py/" title="Sitio web" target="_blank" class="text-light">
                        <i class="fas fa-globe"></i>
                    </a>
                </span>
            </div>
        </div>
    </div>
</footer>
