<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <?php
        if (!isset($titulo) || empty($titulo))
            $titulo = 'Sistema de Gestión Pytyvõ';
        else
            $titulo = $titulo .  ' | ' . Utiles::upper(NOMBRE_SISTEMA);

        echo "<title>$titulo</title>";
        ?>

        <link rel="stylesheet" type="text/css" media="screen" href="<?php echo RUTA_BOOTSTRAP ?>css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" media="screen" href="<?php echo RUTA_FONTAWESOME ?>css/all.min.css">
        <link rel="stylesheet" type="text/css" media="screen" href="<?php echo RUTA_FONTS ?>roboto/css/roboto.css">
        <link rel="stylesheet" type="text/css" media="screen" href="<?php echo RUTA_SELECT2 ?>css/select2.min.css">
        <link rel="stylesheet" type="text/css" media="screen" href="<?php echo RUTA_SELECT2 ?>css/select2-bootstrap4.min.css">
        <link rel="stylesheet" type="text/css" media="screen" href="<?php echo RUTA_CSS ?>estilos.css">
    </head>
    <body>
