
<footer class="pie-pagina-modulos bg-dark pt-3 pb-1 mt-5">
    <div class="container">
        <div class="row">
            <div class="col-6 col-md-4 col-lg-5">
                <h4><?php echo NOMBRE_EMPRESA; ?></h4>
                <ul>
                    <li>
                        <a href="https://www.google.com/maps/place/A+%26+A+Importaciones+S.R.L./@-25.3188651,-57.5637007,17z/data=!3m1!4b1!4m5!3m4!1s0x945da8d6d99878bf:0xbc22af588a104fd4!8m2!3d-25.31887!4d-57.561512?hl=es-ES" title="Dirección" target="_blank" class="text-light">
                            Mecánicos de Aviación 1610 esq. Dr. Félix Paiva
                        </a>
                    </li>
                    <li>Horario de Atención:</li>
                    <li class="elemento-lista-sin-estilo">Lunes a Viernes de 07:40 a 17:00 hs.</li>
                    <li class="elemento-lista-sin-estilo">Sábados de 07:45 a 13:00 hs.</li>
                </ul>
            </div>
            <div class="col-6 col-md-5 col-lg-5">
                <h4>Contacto</h4>
                <ul>
                    <li>Teléfono: (021) 501 005</li>
                    <li>Celular: (0981) 700 011</li>
                    <li>Email: <a href="mailto:ventas@ayaimportaciones.com.py" class="text-light">ventas@ayaimportaciones.com.py</a></li>
                </ul>
            </div>
            <div class="col-12 col-md-3 col-lg-2">
                <div class="row">
                    <div class="col-12 d-flex justify-content-between">
                        <span>
                            <a href="https://www.facebook.com/ayaimportaciones/" title="Facebook" target="_blank" class="text-light">
                                <i class="fab fa-facebook-f fa-2x"></i>
                            </a>
                        </span>
                        <span>
                            <a href="https://www.instagram.com/ayaimportacionessrl/" title="Instagram" target="_blank" class="text-light">
                                <i class="fab fa-instagram fa-2x"></i>
                            </a>
                        </span>
                        <span>
                            <a href="http://www.ayaimportaciones.com.py/" title="Sitio web" target="_blank" class="text-light">
                                <i class="fas fa-globe fa-2x"></i>
                            </a>
                        </span>
                    </div>
                </div>
                <div class="row mt-4">
                    <div class="col-12">
                        <button type="button" class="btn btn-danger btn-sm btn-block" onclick="window.close();">
                            <i class="fas fa-times"></i> Cerrar ventana
                        </button>
                    </div>
                </div>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-12">
                <small class="text-muted"><?php echo NOMBRE_SISTEMA; ?> 0.0.0.1</small>
            </div>
        </div>
    </div>
</footer>
