
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="<?php echo SERVIDOR; ?>">
        <i class="fas fa-hands-helping"></i> <?php echo NOMBRE_SISTEMA; ?>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <?php
                if (defined('NOMBRE_EMPRESA') && strlen(trim(NOMBRE_EMPRESA)) !== 0) {
                    ?>
                    <a class="nav-link" href="#" data-toggle="tooltip" data-placement="bottom" title="<?php echo 'Empresa: ' . Utiles::upper(NOMBRE_EMPRESA); ?>">
                        <i class="fas fa-building"></i>
                        <?php echo '&#160;' . Utiles::upper(NOMBRE_EMPRESA); ?>
                    </a>
                    <?php
                } else {
                    ?>
                    <a class="nav-link" href="#">
                    </a>
                    <?php
                }
                ?>
            </li>
        </ul>
        <ul class="navbar-nav">
            <?php
            if (ControlSesion::sesion_iniciada()) {
                ?>
                <a class="nav-link" href="#">
                    <i class="far fa-clock" aria-hidden="true"></i>
                    <small><?php echo Utiles::obtener_fecha_hora_actual_texto(); ?></small>
                </a>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-user" aria-hidden="true"></i> <?php echo mb_convert_case($_SESSION['usuario'], MB_CASE_UPPER, 'UTF-8'); ?>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="<?php echo RUTA_LOGOUT; ?>">
                            <i class="fas fa-sign-out-alt" aria-hidden="true"></i> Salir
                        </a>
                    </div>
                </li>
                <?php
            }
            ?>
        </ul>
    </div>
</nav>
