
<div class="container">
    <div class="row justify-content-center mt-5 pt-5">
        <div class="card">
            <div class="card-header">
                <h4><b>Sistema de Gestión <?php echo NOMBRE_SISTEMA ?></b></h4>
            </div>
            <div class="card-body">
                <form class="form" role="form" autocomplete="off" method="post" enctype="application/x-www-form-urlencoded" action="<?php echo RUTA_LOGIN; ?>">
                    <input type="hidden" name="token" value="<?php echo random_token(); ?>">
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-12">
                                <label for="inputUsuario" class="label">Nombre de usuario</label>
                                <input type="text" maxlength="25" name="nombre" id="inputUsuario" class="form-control" placeholder="" required autofocus>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-12">
                                <label for="inputClave" class="label">Contraseña</label>
                                <input type="password" maxlength="15" name="clave" id="inputClave" class="form-control" placeholder="" required>
                            </div>
                        </div>
                    </div>

                    <?php
                    if (isset($_POST['login']))
                        $validador->mostrar_error();
                    else {
                        ?>
                        <div class="alert alert-danger alerta-peligro" role="alert" id="error-login"></div>
                        <?php
                    }
                    ?>

                    <button type="submit" class="btn btn-success btn-lg btn-block" name="login">Ingresar</button>
                </form>
            </div>
        </div>
    </div>
    <div class="row mt-3">
        <div class="col-md-12 text-center">
            <p>&#169; 2000-2020, Turtle Software Paraguay</p>
        </div>
    </div>
</div>
