        <script src="<?php echo RUTA_JS ?>utiles.js"></script>
        <script src="<?php echo RUTA_JS ?>monedaValidador.js"></script>
        <script>
            $(function() {
                if ($('#error-nombre').length)
                    if ($('#error-nombre').text().trim().length)
                        $('#error-nombre').css('display', 'block');

                if ($('#error-simbolo').length)
                    if ($('#error-simbolo').text().trim().length)
                        $('#error-simbolo').css('display', 'block');
            });
        </script>
