
<?php
if (isset($mensaje) && !empty($mensaje))
    Utiles::mostrar_mensaje($mensaje);
?>

<input type="hidden" name="codigo"
    value="<?php echo $modelo->obtener_codigo(); ?>">

<div class="form-group">
    <label for="nombre">Nombre</label>
    <input type="text" class="form-control text-uppercase" id="nombre"
        value="<?php echo Utiles::escapar_salida($modelo->obtener_nombre()); ?>" readonly>
</div>

<div class="form-group">
    <label for="simbolo">Símbolo</label>
    <input type="text" class="form-control" id="simbolo"
        value="<?php echo Utiles::escapar_salida($modelo->obtener_simbolo()); ?>" readonly>
</div>

<div class="form-check mb-3">
    <input type="checkbox" class="form-check-input" id="decimales"
        <?php if ($modelo->utiliza_decimales()) echo 'checked'; ?>
        disabled readonly>
    <label class="form-check-label" for="decimales">Decimales</label>
</div>

<div class="form-check mb-3">
    <input type="checkbox" class="form-check-input" id="vigente"
        <?php if ($modelo->esta_vigente()) echo 'checked'; ?>
        disabled readonly>
    <label class="form-check-label" for="vigente">Vigente</label>
</div>
